import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Eye, HandHeart, ScrollText } from "lucide-react";

export const metadata: Metadata = { title: "Our Story", description: "Learn how ST Thangka approaches Himalayan Buddhist art, curation, and collector care." };

export default function AboutPage() {
  return <div className="bg-[#fbfaf7]">
    <section className="section-shell grid min-h-[70svh] items-center gap-12 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-24"><div className="animate-rise"><p className="eyebrow">Our story</p><h1 className="font-serif text-5xl leading-[1.02] sm:text-7xl">Art chosen for what it <em className="text-[#a7442d]">carries.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-black/60">ST Thangka exists to make the experience of discovering sacred Himalayan art more thoughtful, transparent, and personal.</p></div><div className="relative aspect-[4/4.7] overflow-hidden bg-[#ded8cd]"><Image src="/thangka-hero.png" alt="A framed thangka painting in a contemplative interior" fill priority sizes="(min-width:1024px) 50vw,100vw" className="object-cover object-[70%_center]"/></div></section>
    <section className="bg-[#17211c] py-20 text-white lg:py-28"><div className="section-shell grid gap-12 lg:grid-cols-2"><p className="font-serif text-4xl leading-tight sm:text-5xl">A thangka is not simply an object for a wall. It is image, teaching, discipline, and devotion held together.</p><div className="space-y-5 text-base leading-8 text-white/62"><p>Our role is to help each collector slow down and see more: the subject, the symbolism, the visual balance, and the practical realities of living with a work.</p><p>We favour clear information and patient guidance. Whether you are beginning a meditation space, choosing a meaningful gift, or building a collection, the decision should feel informed and unhurried.</p></div></div></section>
    <section className="section-shell py-20 lg:py-28"><div className="mb-12 max-w-2xl"><p className="eyebrow">How we work</p><h2 className="section-title">Care at every <span>step.</span></h2></div><div className="grid border-y border-black/15 md:grid-cols-3 md:divide-x md:divide-black/15"><Value icon={Eye} number="01" title="Look closely" text="We consider visual quality, subject, condition, and the details a collector needs to understand the work."/><Value icon={ScrollText} number="02" title="Share context" text="We present available information clearly and make room for questions before any purchase."/><Value icon={HandHeart} number="03" title="Support the journey" text="From choosing and packing to placement and aftercare, we remain available beyond checkout."/></div></section>
    <section className="bg-[#d9b86c] py-18"><div className="section-shell flex flex-col items-start justify-between gap-8 sm:flex-row sm:items-center"><h2 className="max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Find the work that feels right for your space.</h2><Link href="/products" className="premium-button">View collection <ArrowRight className="h-4 w-4"/></Link></div></section>
  </div>;
}
function Value({icon:Icon,number,title,text}:{icon:typeof Eye;number:string;title:string;text:string}) { return <article className="py-9 md:px-8 md:py-12 first:pl-0"><div className="flex items-center justify-between"><Icon className="h-7 w-7 text-[#a7442d]"/><span className="text-xs font-bold text-black/30">{number}</span></div><h3 className="mt-12 font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-black/55">{text}</p></article>; }
